version: '3.9'

services:
  frontend:
    container_name: ontrack-frontend
    hostname: ontrack-frontend
    image: ghcr.io/robinkiefer2001/ontrack-frontend:latest
    environment:                          # ← "env" → "environment"
      - BACKEND_URL=http://ontrack-backend:8080
      - AUTHENTIK_CLIENT_ID=ontrack-client
      - AUTHENTIK_CLIENT_SECRET=${PROD_GLOBAL_AUTHENTIK_ONTRACK_CLIENT_SECRET}
      - AUTHENTIK_ISSUER=https://auth.informait.ch/application/o/ontrack/
      - AUTHENTIK_AUTH_SECRET=${PROD_FRONTEND_AUTHENTIK_ENCRYPTION_SECRET}
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`ontrack.informait.ch`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=le"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

networks:
  web:
    external: false