version: '3.9'
services:
  frontend:
    container_name: ontrack-frontend
    image: ghcr.io/robinkiefer2001/ontrack-frontend:latest
    hostname: ontrack-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile