name: frontend-deploy-containers

on:
  workflow_run:
    workflows: ["build-images"]
    types:
      - completed

permissions:
  contents: read
  packages: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: add ssh key
        run: |
          mkdir -p ./ssh
          echo "${{ secrets.PROD_RUNNER_SSH_KEY }}" > "./ssh/id_rsa"
          chmod 600 "./ssh/id_rsa"

      - name: Create deployment directory
        run: |
          ssh -i "./ssh/id_rsa" -o StrictHostKeyChecking=no \
            "${{ vars.PROD_DEPLOYMENT_USER }}"@"${{ vars.PROD_DEPLOYMENT_ENDPOINT }}" \
            "mkdir -p ~/var/opt/ontrack"

      - name: copy docker-compose-deploy
        run: |
          scp -o StrictHostKeyChecking=no -i ./ssh/id_rsa \
            docker-compose-deploy.yml \
            "${{ vars.PROD_DEPLOYMENT_USER }}"@"${{ vars.PROD_DEPLOYMENT_ENDPOINT }}":~/var/opt/ontrack/docker-compose-deploy.yml
            
      - name: docker compose pull
        run: |
          ssh -o StrictHostKeyChecking=no -i ./ssh/id_rsa \
            "${{ vars.PROD_DEPLOYMENT_USER }}"@"${{ vars.PROD_DEPLOYMENT_ENDPOINT }}" \
            '
            docker compose -f ~/var/opt/ontrack/frontend-docker-compose-deploy.yml pull
            docker pull postgres:latest
            '

      - name: Stop old containers (if any)
        run: |
          ssh -o StrictHostKeyChecking=no -i ./ssh/id_rsa \
            "${{ vars.PROD_DEPLOYMENT_USER }}"@"${{ vars.PROD_DEPLOYMENT_ENDPOINT }}" \
            '
            docker compose -f ~/var/opt/ontrack/frontend-docker-compose-deploy.yml down || true
            '

  build_images:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: add ssh key
        run: |
          mkdir -p ./ssh
          echo "${{ secrets.PROD_RUNNER_SSH_KEY }}" > "./ssh/id_rsa"
          chmod 600 "./ssh/id_rsa"

      - name: Start Containers
        run: |
          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=5 -i ./ssh/id_rsa \
            "${{ vars.PROD_DEPLOYMENT_USER }}"@"${{ vars.PROD_DEPLOYMENT_ENDPOINT }}" \
            "
            docker compose -f ./var/opt/ontrack/frontend-docker-compose-deploy.yml up -d
            "